// The Fibonacci sequence is a series of numbers that starts with 0 & 1 and the rest of the numbers are generated by adding the immediate two numbers before it. 
// It goes like this: 0, 1, 1, 2, 3, 5, 8,13, 21, 34, 55, 89, 144 and so on.
// In short, fibonacci(0) = 0, fibonacci(1) = 1 and fibonacci(n) = fibonacci(n-1) + fibonacci(n-2)

public class LAB9HW4{
  public static void main(String [] args){
    System.out.println(fibonacci(9));
  }
  public static int fibonacci(int x){
    if (x == 0){
      return 0;
    }
    else if (x == 1){
      return 1;
    }
    else{
      return fibonacci(x - 1) + fibonacci(x - 2);
    }
  }
}

//Took help from claude. 
